### ISSUE TITLE
List all target journals

### ISSUE THREAD

**Issue by dkurman** [dkurman/handwriting_recognition#12]
Create a list of all target journals. Provide the key dates and publication expenses.

**Comment by nurseitovdb** [comment]
[**IJDAR: International Journal on Document Analysis and Recognition**](https://link.springer.com/journal/10032)

Sponsored by the International Association for Pattern Recognition, this journal is focused on publishing articles that cover all areas related to document analysis and recognition. This includes contributions dealing with computer recognition of characters, symbols, text, lines, graphics, images, handwriting, signatures, as well as automatic analyses of the overall physical and logical structures of documents, with the ultimate objective of a high-level understanding of their semantic content.

The International Journal on Document Analysis and Recognition (IJDAR) publishes articles of four primary types: original research papers, correspondence, overviews and summaries, and system descriptions. It also features special issues on active areas of research.

_Indexing:_
- [Scopus](https://www.scopus.com/sourceid/130138): SJR 2017 - 0.456

_Paper samples:_
- [KERTAS: dataset for automatic dating of ancient Arabic manuscripts](https://link.springer.com/content/pdf/10.1007%2Fs10032-018-0312-3.pdf)
- [Attribute CNNs for word spotting in handwritten documents](https://sci-hub.tw/https://doi.org/10.1007/s10032-018-0295-0)
- [Integrating scattering feature maps with convolutional neural networks for Malayalam handwritten character recognition](https://sci-hub.tw/https://doi.org/10.1007/s10032-018-0308-z)
