### ISSUE TITLE
List all target conferences

### ISSUE THREAD

**Issue by dkurman** [dkurman/handwriting_recognition#13]
Create a list of all target conferences. Provide key dates and expenses.

**Comment by nurseitovdb** [comment]
[**ICFHR 2020: INTERNATIONAL CONFERENCE ON FRONTIERS IN HANDWRITING RECOGNITION**
](http://icfhr2020.tu-dortmund.de/)
_Dortmund, Germany_
_September 8 – 10, 2020_

The International Conference on Frontiers of Handwriting Recognition (ICFHR), formerly called International Workshop on Frontiers of Handwriting Recognition (IWFHR), is the most important scientific venue in the field of handwriting recognition.  The aim of this conference is to bring together international experts from academia and industry to share their experiences and to promote research and development in all aspects of handwriting recognition and applications.

_Deadlines:_ to be announced.
_Costs:_ to be announced.

**Comment by nurseitovdb** [comment]
[**ICDAR 2019 : International Conference on Document Analysis and Recognition**
](http://www.icdar2019.org/)

_Sydney, Australia_
_September 20 – 25, 2019_

ICDAR is a very successful and flagship conference series, which is the biggest and premier international gathering for researchers, scientist and practitioners in the document analysis community. 
University of Technology Sydney (UTS), Australia
The accepted papers will be published by Conference Publishing Services (CPS) and will be submitted to IEEE Xplore Digital Library.

[_Deadlines:_](http://icdar2019.org/dates/) March 01, 2019
_Costs:_ not provided.

**Comment by nurseitovdb** [comment]
[**CBDAR 2019: 8th International Workshop on Camera-Based Document Analysis & Recognition**](https://cbdar2019.univ-lr.fr/)

_France_
_September 22, 2019_

The CBDAR series has a special focus on the analysis of camera captured documents and text. CBDAR is a forum for presenting up-to-date research, sharing experiences and fomenting discussions on future directions. The goal of CBDAR is to explore new research directions through the presentation of up-to-date research as well as discussions on future directions.
Submission Deadline (normal papers) | 

[_Deadlines:_](https://cbdar2019.univ-lr.fr/important-dates/) May 10, 2019 
_Costs:_ not provided.

**Comment by nurseitovdb** [comment]
[**CVPR 2019: Computer Vision and Pattern Recognition**](http://cvpr2019.thecvf.com/) 
_Long Beach, CA, USA_
_June 16 - 21, 2019_

CVPR is the premier annual computer vision event comprising the main conference and several co-located workshops and short courses. 
[_Deadlines:_](http://cvpr2019.thecvf.com/submission/timeline) November 16, 2018.
_Costs:_ registration $450-1200

**Comment by nurseitovdb** [comment]
[IWPR 2019: International Workshop on Pattern Recognition](http://www.icopr.org)
_Nanjing, China_
_June 28-30, 2019_ 

The IWPR encompasses all technical aspects of specifying, developing and evaluating the theoretical underpinnings and applied mechanisms of the AI-based components of computer tools such as algorithms, architectures and languages.

_Deadlines:_
- Submission Deadline: March 20, 2019
- Acceptance Notification: April 10, 2019
- Registration Deadline: April 25, 2019

_Costs:_
- Registration Fee: $580

**Comment by nurseitovdb** [comment]
[**ICCV 2019: International Conference on Computer Vision**](http://iccv2019.thecvf.com/)

_Seoul, Korea_ 
_Oct 27 - Nov 2, 2019_

ICCV is the premier international computer vision event comprising the main conference and several co-located workshops and tutorials. With its high quality and low cost, it provides an exceptional value for students, academics and industry researchers.

_Deadlines:_ 
- Paper Registration Deadline: March 15, 2019 (11:59PM PST)
- Paper Submission Deadline: March 22, 2019 (11:59PM PST)

_Costs:_

**Comment by nurseitovdb** [comment]
[**BMVC 2019: 30th British Machine Vision Conference**](https://bmvc2019.org/)

_Cardiff, Great Britain_
_9-12 September 2019_

The British Machine Vision Conference (BMVC) is the British Machine Vision Association (BMVA) annual conference on machine vision, image processing, and pattern recognition. It is one of the major international conferences on computer vision and related areas held in the UK. With increasing popularity and quality, it has established itself as a prestigious event on the vision calendar.

[_Deadlines:_](https://bmvc2019.org/dates/) 
- Workshop Submission deadline: 31 March 2019
- Submission Deadline (final, no extensions): 29 April 2019

_Costs:_ not declared yet.

_Paper samples:_
- [An Efficient End-to-End Neural Model for Handwritten Text Recognition](http://bmvc2018.org/contents/papers/0606.pdf)
- [Adaptive Context-aware Reinforced Agent for Handwritten Text Recognition](http://bmvc2018.org/contents/papers/0628.pdf)
- [Chinese Handwriting Imitation with Hierarchical Generative Adversarial Network](http://bmvc2018.org/contents/papers/1141.pdf)
