### ISSUE TITLE
installation instructions

### ISSUE THREAD

**Issue by dkurman** [dkurman/handwriting_recognition#20]

**Comment by bosskairat** [comment]
Для соблюдения версионности используем Miniconda3
Скачать можно по ссылке https://docs.conda.io/en/latest/miniconda.html
Преимущество Miniconda от virtualenv, то что он устанавливает python на локальную директорию, а не использует системный python как virtualenv. Это дает нам возможность переноса виртуальной среды в любое другое место, вместе со всеми библиотеками, включая сам python нужной версии. 
Чтобы создать виртуальную среду в miniconda, используем следующую команду:
# conda create -n venv python==3.7.1
активация виртуальной среды
# conda activate venv 
Необходимые библиотеки требующие установку будем хранить в файле requirements.txt
Установка программ из файла requirements.txt:
# pip install -r requirements.txt
